FROM php:7.2-fpm-alpine

# Install Deps
RUN apk update && apk add --no-cache \
    $PHPIZE_DEPS \
    && docker-php-ext-install pdo_mysql

# Run PECL
RUN pecl install xdebug-2.6.0 \
    && docker-php-ext-enable xdebug

WORKDIR /application

# Copy configuration
COPY php.ini /usr/local/etc/php/conf.d/docker-php.ini